# Generated by Django 4.2.13 on 2025-10-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='duration_min',
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
